from model.call_back_data.type import TypeProfessionalBackData, TypeBeginnerCallBackData, TypeProceedingCallBackData
from model.call_back_data.login import LoginNoCallBackData, LoginYesCallBackData
from model.call_back_data.task import TaskNoCallBackData, TaskYesCallBackData

