from model.handlers.user import user_router
from model.handlers.admin import admin_router
from model.handlers.login import login_router
from model.handlers.weather import weather_router
from model.handlers.back_to_menu import back_to_menu_router
from model.handlers.currency import currency_router
from model.handlers.cat import cat_router
from model.handlers.poll import poll_router
from model.handlers.cabinet import cabinet_router
from model.handlers.erro import error_router
